changelog:
  categories:
    - title: Enhancement
      labels:
          - enhancement
    - title: Bug Fixs
      labels:
          - bug
          - fixes
  exclude:
    labels:
        - dependencies
    authors:
        - dependabot