name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This is error" #Errorレベルのアノテーション
      - run: echo "::warning::This is a warning" #Warningレベルのアノテーション
      - run: echo "::notice::This is notice" #Noticeレベルのアノテーション