name: Environments

on:
  workflow_dispatch:
    inputs:
      environment-name:
        description: 'Environment name'
        required: false
        default: 'test'

jobs:
  print:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment-name }}  # この方法で入力を参照
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "Username is set"  # セキュリティ保護されたシークレットのため表示は避けます
      - run: |
          echo "First character of password is: ${PASSWORD:0:1}"
          echo "Rest of the password: ${PASSWORD#?}"