name: Manual matrix
on: push
jobs:
    print:
        strategy:
            matrix:
                include:
                - os: ubuntu-latest
                  version: 20
                - os: macos-latest
                  version: 18
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/setup-node@v4
              widh:
                  node-version: ${{ matrix.version }}
            - run: echo "${RUNNER_OS}" && node --version