name: Multi-dimension matrix
on: push
jobs:
    print:
      strategy:
          matrix:
              os: [ubuntus-latest, macos-latest]
              version: [18, 20]
      runs-on: ${{ matrix.os }}
      steps:
          - uses: actions/setup-node@v4
            with:
              node-version: ${{ matrix.version }} #versionプロパティの参照
          - run: echo "${RUNNER_OS} && node --version"